### PR TITLE
Remove stale copybara.

### PR DESCRIPTION
**Pull request by JamesMBartlett**
Summary: Removes copybara config that was previously used for copying changes across repos.

Type of change: /kind cleanup

Test Plan: This jenkins job is already disabled, so should be no functional changes.
Will test that jenkins still works.

### CODE REVIEW

**Comment by JamesMBartlett** [comment]
@pixie-labs-buildbot test this please

**Comment by vihangm** [comment]
test this please

**Comment by JamesMBartlett** [comment]
test this please

**Comment by JamesMBartlett** [comment]
@pixie-labs-buildbot test this please

**Review by aimichelle — APPROVED** [review]

**Pull request merged**
