### PR TITLE
Add WSO2 to adopters list

### PR DESCRIPTION
**Pull request by tharinduwijewardane**
### Description:
Add WSO2 to adopters list

### CODE REVIEW

**Comment by aimichelle** [comment]
@pixie-labs-buildbot , test this please.

**Review by aimichelle — APPROVED** [review]

**Comment by tharinduwijewardane** [comment]
@aimichelle we need to edit the website url to `https://wso2.com/choreo/` shall i send a update to this pr or send a new pr ?

**Comment by tharinduwijewardane** [comment]
@aimichelle could you please approve again ?

**Review by aimichelle — APPROVED** [review]

**Comment by aimichelle** [comment]
@tharinduwijewardane , would you mind signing your commit by following this guide? https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification Thank you!

**Comment by tharinduwijewardane** [comment]
@aimichelle Done. I force pushed a new verified commit with the change.

**Review by aimichelle — APPROVED** [review]

**Pull request merged**
