### PR TITLE
[socket tracer] Add context to E|D CHECKs in files `parser.cc` and `sticher.cc`.

### PR DESCRIPTION
**Pull request by etep**
Summary: We implement `CTX_ECHECK` and `CTX_DCHECK` inside of the protocols sub-tree of the socket tracer. Previously, if any E or D check fired, the error message would not specify which protocol triggered the problem. This new macro guarantees that the full file path is printed with any failure.

Type of change: /kind feature

Test Plan: Existing test coverage.

### CODE REVIEW

**Review by ddelnano — APPROVED** [review]
This approach sounds good to me. In addition I read through the glog docs to see if there was any feature for dealing with this situation and didn't find any remedy.

**Review by vihangm — CHANGES_REQUESTED** [review]
It seems like the OP versions already handle this in glog, but our ECHECK macros do not.
https://github.com/google/glog/blame/bc1fada1cf63ad12aee26847ab9ed4c62cffdcf9/src/glog/logging.h.in#L889
https://github.com/pixie-io/pixie/blob/97d13beb734c8a5be8eacd38757b1b7a1e421caa/src/common/base/logging.h#L62-L68

We should 1) consider upgrading log and 2) update our ECHECK macro instead.
Additionally if we end up needing to add this additional macro, maybe add the line number with `__LINE__` too just like glog does it.

**Comment by etep** [comment]
@vihangm Can you please be more specific about the direction you are advocating?

**Comment by vihangm** [comment]
> @vihangm Can you please be more specific about the direction you are advocating?

Upgrade glog to see if it includes context for DCHECKs. Unless I'm mistaken the macros seem to suggest it should include context.
Update our ECHECK macro to match the CHECK/DCHECH impls so that it also includes context (assuming that step 1 works).

**Review by vihangm — APPROVED** [review]

**Comment by vihangm** [comment]
Gotcha, option 2 makes sense.

**Pull request merged**
