### PR TITLE
[third_party] Bump simdutf version

### PR DESCRIPTION
**Pull request by silvergasp**
Summary: The latest version of simdutf has various security and performance improvements.

Relevant Issues: Fixes the following vulnerabilities.
https://osv.dev/vulnerability/OSV-2023-281
https://osv.dev/vulnerability/OSV-2023-278
https://osv.dev/vulnerability/OSV-2023-272

Type of change: /kind cleanup

Test Plan: N/A

### CODE REVIEW

**Comment by JamesMBartlett** [comment]
@pixie-io-buildbot test this please

**Comment by JamesMBartlett** [comment]
Hi there. Thanks for your contribution.
Could you please follow our PR description template? 

Also could you please GPG sign your commit (instructions here: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

**Comment by silvergasp** [comment]
> Hi there. Thanks for your contribution. Could you please follow our PR description template?
> 
> Also could you please GPG sign your commit (instructions here: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

Signed, strangely I didn't get prompted with the PR template, updated now :)

**Comment by JamesMBartlett** [comment]
I think you might've not hit save on the PR description change fyi

**Comment by silvergasp** [comment]
> I think you might've not hit save on the PR description change fyi

Whoops! I think thats updated now

**Comment by silvergasp** [comment]
Weirdly I can't see the build failure, all I can see is `WARNING: Bazel build failed`

**Comment by JamesMBartlett** [comment]
> Weirdly I can't see the build failure, all I can see is `WARNING: Bazel build failed`

The logs are weirdly placed in the step above that, which has a green check next to it. Also here: https://bb.px.dev/invocation/83231f1c-8f80-4081-8393-d9a58fee474d

Seems like they renamed the cmake option `BUILD_TESTING` to `SIMDUTF_TESTS`, so if you could update `bazel/external/simdutf.BUILD` that would be great

**Comment by JamesMBartlett** [comment]
@pixie-io-buildbot test this please

**Comment by JamesMBartlett** [comment]
Hmm, it seems like they actually now use both `BUILD_TESTING` and `SIMDUTF_TESTS`, could you disable `BUILD_TESTING` as well as `SIMDUTF_TESTS`

**Comment by silvergasp** [comment]
Odd I did build it before submitting with `bazelisk build @com_github_simdutf_simdutf//...` and it worked fine. In any case I've made the suggested changes and it builds locally fine.

**Comment by JamesMBartlett** [comment]
@pixie-io-buildbot test this please

**Comment by JamesMBartlett** [comment]
> Odd I did build it before submitting with `bazelisk build @com_github_simdutf_simdutf//...` and it worked fine. In any case I've made the suggested changes and it builds locally fine.

For whatever reason, the simdutf test binaries fail to build under `gcc` and not clang so if you run `bazel build --config=gcc @com_github_simdutf_simdutf//...` without the newest changes I suspect it would fail.

**Comment by JamesMBartlett** [comment]
Sorry about the PR description linter. I just put out a PR so that it shows all the errors the first time instead of one by one like you're experiencing (#1237)

**Review by JamesMBartlett — APPROVED** [review]

**Pull request merged**
