### PR TITLE
Revive the protocol_inference code and set it up to run under bazel

### PR DESCRIPTION
**Pull request by ddelnano**
Summary: Revive the protocol inference analysis code and set it up to run under bazel

The protocol inference tooling is important for verifying that stirling's protocol parsing is accurate. When pixie traces a network connection it tries to infer what protocol the connection is using. Whatever protocol is inferred will determine what parser Pixie uses for the lifetime of a connection. Identifying the protocol incorrectly means that all of the data for that connection will be parsed incorrectly. Therefore it's critical to verify that each protocol is detected accurately and isn't mislabeled as another protocol.

The code added in this PR was taken mostly wholesale from the previous code. I also removed the dependence on matplotlib since it's image generation depends on Pillow, which has a problematic license. The confusion matrix is now a text based table and uses `termcolor` to replace the cell coloring (as seen in the image below).

Type of change: /kind test-infra

Test Plan: Ran the dataset and confusion matrix generation through `bazel run` as seen below (read PR comments below for details)

- Verified the new text based confusion matrix is colored and matches the reference matrix
Screen Shot 2023-02-08 at 9 13 51 AM

<details><summary>Output of data and confusion matrix generation commands</summary>

```
INFO: Running command line: bazel-bin/src/stirling/protocol_inference/dataset_generation --dataset /home/ddelnano/code/protocol_inference/protocol_data/
INFO: Streaming build results to: https://bb.corp.pixielabs.ai/invocation/41e20f4a-81e8-4540-bac6-0abf34bda4b1
INFO: Build completed successfully, 1 total action
tshark -2 -r {pcap_file} -T fields     -e tcp.payload     -e udp.payload     -e frame.protocols     -e ip.src     -e ip.dst     -e tcp.srcport     -e udp.srcport     -e tcp.dstport     -e udp.dstport -e mysql.packet_length -e pgsql.length -e amqp.length > {output_file}
Processing capture:  f8pbCaptures
Processing pod:  bash-79f9458677-7wwq9
Processing pod:  profile-server-f77dcddf9-dl8jk
Processing pod:  pl-nats-2
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/f8pbCaptures/pl-nats-2/2049483.pcapng" appears to be damaged or corrupt.
(pcapng: total block length 1075694512 is too large (> 134348832))
Processing pod:  .DS_Store
Processing pod:  kube-proxy-gke-prod-pool-3-daf93b39-f8pb
Processing pod:  profile-server-5bf948d66b-j7xl5
Processing pod:  project-manager-server-56b5bcfb9c-hj64j
Processing pod:  pl-elastic-es-data-2
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/f8pbCaptures/pl-elastic-es-data-2/23435.pcapng" appears to be damaged or corrupt.
(pcapng: total block length 1932851800 is too large (> 134348832))
Processing pod:  pl-stan-0
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/f8pbCaptures/pl-stan-0/2649258.pcapng" appears to be damaged or corrupt.
(pcapng: total block length 168296708 is too large (> 134348832))
Processing pod:  pl-elastic-es-data-1
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/f8pbCaptures/pl-elastic-es-data-1/179328.pcapng" appears to be damaged or corrupt.
(pcapng: total block lengths (first 9956 and second 4030733060) don't match)
Processing pod:  nri-bundle-newrelic-logging-788kl
Processing pod:  scriptmgr-server-db6964954-w9kc2
Processing pod:  pl-elastic-es-master-2
Processing pod:  cloud-proxy-d577b67d5-pgj5s
Processing pod:  pl-stan-4
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/f8pbCaptures/pl-stan-4/2656276.pcapng" appears to be damaged or corrupt.
(pcapng: total block length 2135183916 is too large (> 134348832))
Processing pod:  kube-dns-6d5b45496c-2xgb5
Processing pod:  scriptmgr-server-b5686b966-7277v
Processing pod:  vizier-pem-mc28c
Processing pod:  project-manager-server-668fd669b4-npw2j
Processing pod:  pl-elastic-es-master-1
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/f8pbCaptures/pl-elastic-es-master-1/179836.pcapng" appears to be damaged or corrupt.
(pcapng: total block lengths (first 13308 and second 3808225676) don't match)
Processing pod:  slackin-server-67758fd4db-k5pzr
Processing pod:  vzmgr-server-68d56cb466-grkmr
Processing pod:  nri-bundle-newrelic-infrastructure-9dzz2
Processing pod:  db-reader-58ddd8786c-f7vvw
Processing pod:  api-server-b8cbb5c44-w6wvn
Processing pod:  pl-nats-4
Processing pod:  nri-bundle-nri-kube-events-5dccff7cfb-mf9vk
Processing pod:  vzconn-server-669c4b7c48-87c4j
Processing capture:  5mpfCaptures
Processing pod:  auth-server-56fc547f8c-7tg87
Processing pod:  nri-bundle-newrelic-infrastructure-btcq7
 ** (tshark:467203) 12:35:05.372777 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 105714: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467203) 12:35:05.372888 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 105714: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467203) 12:35:06.633195 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 129565: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467203) 12:35:06.633265 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 129565: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467203) 12:35:06.634780 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 129566: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467203) 12:35:06.634818 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 129566: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
Processing pod:  vizier-query-broker-5569d78797-djbzj
Processing pod:  log-collector-7675ddf7cc-r5bwc
Processing pod:  .DS_Store
Processing pod:  api-server-b8cbb5c44-2smnq
Processing pod:  pl-stan-3
Processing pod:  indexer-server-6c7c778588-hkfhp
Processing pod:  nri-bundle-nri-metadata-injection-7c7d64c6fb-pqc8t
Processing pod:  api-server-788fb5b568-csc6c
Processing pod:  artifact-tracker-server-6bb96f8666-sksmc
Processing pod:  pl-stan-2
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/5mpfCaptures/pl-stan-2/2731184.pcapng" appears to be damaged or corrupt.
(pcapng: total block length 1694336752 is too large (> 134348832))
Processing pod:  pl-nats-3
Processing pod:  auth-server-577685cd85-82kx8
Processing pod:  pl-elastic-es-master-0
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/5mpfCaptures/pl-elastic-es-master-0/2576327.pcapng" appears to be damaged or corrupt.
(pcapng: total block length 1052528140 is too large (> 134348832))
Processing pod:  pl-nats-0
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/5mpfCaptures/pl-nats-0/91066.pcapng" appears to be damaged or corrupt.
(pcapng: Not enough data to handle option of length 2320)
Processing pod:  pl-nats-1
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/5mpfCaptures/pl-nats-1/1648866.pcapng" appears to have been cut short in the middle of a packet.
Processing pod:  bash3-5fc96c4cf8-wv5sp
Processing pod:  scriptmgr-server-db6964954-bms57
Processing pod:  vizier-proxy-7c75497cdd-6n7rc
Processing pod:  nri-bundle-kube-state-metrics-c4d69d8c4-42lll
 ** (tshark:467286) 12:35:13.421795 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 384: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467286) 12:35:13.421890 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 384: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467286) 12:35:13.523671 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 1083: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467286) 12:35:13.523717 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 1083: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467286) 12:35:13.623143 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 1782: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467286) 12:35:13.623203 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 1782: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
Processing pod:  profile-server-f77dcddf9-bvqwq
Processing pod:  indexer-server-6944cf9d75-glkmd
Processing pod:  pl-elastic-es-master-1
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/5mpfCaptures/pl-elastic-es-master-1/2578921.pcapng" appears to be damaged or corrupt.
(pcapng: total block lengths (first 14180 and second 3297138104) don't match)
Processing pod:  pl-elastic-es-data-0
Processing pod:  vizier-pem-snqvw
 ** (tshark:467307) 12:35:22.361855 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 127799: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467307) 12:35:22.361946 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 127799: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
Processing pod:  kube-proxy-gke-prod-pool-3-daf93b39-5mpf
 ** (tshark:467315) 12:35:31.022452 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 120245: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467315) 12:35:31.022537 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 120245: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
Processing pod:  cloud-proxy-75d896687b-9pv9d
Processing pod:  nri-bundle-newrelic-logging-lqhjk
 ** (tshark:467325) 12:35:40.246095 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 117679: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
 ** (tshark:467325) 12:35:40.246182 [Epan WARNING] -- Dissector bug, protocol HTTP, in packet 117679: ./epan/packet.c:812: failed assertion "saved_layers_len < 500"
Processing pod:  elastic-operator-0
Processing pod:  vzconn-server-7f69589549-g597g
Processing capture:  56glCaptures
Processing pod:  nri-bundle-newrelic-logging-dqcdl
Processing pod:  profile-server-5bf948d66b-t9r94
Processing pod:  pl-nats-2
Processing pod:  api-server-b8cbb5c44-7j8rb
Processing pod:  l7-default-backend-5b76b455d-bx2j5
Processing pod:  .DS_Store
Processing pod:  vizier-pem-gfk46
Processing pod:  cloud-proxy-d577b67d5-wdzkl
Processing pod:  kube-dns-autoscaler-5c78d65cd9-wt6ww
Processing pod:  nri-bundle-newrelic-infrastructure-78hlr
Processing pod:  api-server-788fb5b568-pm7f9
Processing pod:  pl-stan-2
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/56glCaptures/pl-stan-2/2529526.pcapng" appears to be damaged or corrupt.
(pcapng: total block length 1325017220 is too large (> 134348832))
Processing pod:  scriptmgr-server-db6964954-8mcs7
Processing pod:  nats-operator-7d686798f4-czvgz
Processing pod:  project-manager-server-56b5bcfb9c-s48kf
Processing pod:  pl-nats-0
Processing pod:  project-manager-server-668fd669b4-ps5b5
Processing pod:  auth-server-577685cd85-w9xgx
Processing pod:  kube-dns-6d5b45496c-q7gxm
Processing pod:  pl-stan-1
tshark: The file "/home/ddelnano/code/protocol_inference/protocol_data/56glCaptures/pl-stan-1/2525487.pcapng" appears to be damaged or corrupt.
(pcapng: total block length 1290324776 is too large (> 134348832))
Processing pod:  bash2-6c9cd44d64-qsqfn
Processing pod:  cloud-proxy-75d896687b-95x5f
Processing pod:  metrics-server-v0.3.6-547dc87f5f-hmd97
Processing pod:  vzmgr-server-758df8c99d-hg4ll
Processing pod:  log-collector-87d4bc976-q9l2g
Processing pod:  nri-bundle-nri-prometheus-648d84b69f-bm9cd
Processing pod:  kube-proxy-gke-prod-pool-3-daf93b39-56gl
Processing pod:  auth-server-56fc547f8c-6tjxb
Processing pod:  scriptmgr-server-b5686b966-f9lrg
Processing pod:  artifact-tracker-server-676b95bc44-jgmg2
Processing capture:  toyCaptures
Processing pod:  kube-proxy-gke-dev-cluster-rcheng-default-pool-d51c17e8-rrv0
Processing pod:  orders-5659fcf7fc-c2x7r
Processing pod:  payment-7f95f9f77-gklbv
Processing pod:  catalogue-69b7ff5bb4-2p5rt
Processing pod:  .DS_Store
Processing pod:  cartservice-5c6c869576-m6r9v
Processing pod:  queue-master-77c59f6d79-q6kvn
Processing pod:  metrics-server-v0.3.6-547dc87f5f-kkw8z
Processing pod:  rabbitmq-c7b9db6cc-nrpd9
Processing pod:  paymentservice-56bfbb9f45-52xjg
Processing pod:  vizier-proxy-5c4c576bc-qsgp5
Processing pod:  currencyservice-5ff5647975-49csd
Processing pod:  kube-dns-autoscaler-5c78d65cd9-gr8hc
Processing pod:  catalogue-db-69cf48ff8-m5wvm
Processing pod:  redis-cart-5f59546cdd-xnnbk
Processing pod:  carts-84cd4fbf9b-pjsxp
Processing pod:  emailservice-bd7dff65c-r6ssd
Processing pod:  vizier-query-broker-57b569dc46-wkhm2
Processing pod:  l7-default-backend-5b76b455d-ckzvj
Processing pod:  shipping-64c45cd9bc-ncwh9
Processing pod:  recommendationservice-f54c77bdc-j2j5p
Processing pod:  carts-db-64ff6c747f-zz477
Processing pod:  vizier-metadata-0
Processing pod:  pl-nats-1
Processing pod:  session-db-67fd8d6d7-l7lnk
Processing pod:  adservice-f769fb867-jztj9
Processing pod:  kube-dns-6d5b45496c-692m8
Processing pod:  load-test-65c76b4869-5k6xq
Processing pod:  user-db-87f548457-t5785
Processing pod:  productcatalogservice-dbf8bfc5c-4hnvb
Processing pod:  user-559d7f794f-9b8ll
Processing pod:  shippingservice-84b4d59949-mh4v2
Processing pod:  orders-db-df75f545f-9dkww
Processing pod:  checkoutservice-867cb5956f-k8hs9
Processing pod:  kelvin-6bb688c5d-9nknc
Processing pod:  nats-operator-7d686798f4-l9tfr
Processing pod:  loadgenerator-74ffdb94fc-xdjgh
Processing pod:  front-end-6fc8dff6ff-cjks9
Processing pod:  vizier-certmgr-78b7bdd56f-rwr2l
Processing pod:  vizier-cloud-connector-8fb5868bf-f56gs
Processing pod:  frontend-85d7bd855-w2vmm
Processing pod:  vizier-pem-zkzgt

ddelnano@turing:~/code/pixie$ bazel run src/stirling/protocol_inference:eval  -- --dataset ~/code/protocol_inference/protocol_data/packet_dataset.tsv --num_workers 8 --batch 256 --model ruleset_basic --output_dir ~/code/protocol_inference/
INFO: Streaming build results to: https://bb.corp.pixielabs.ai/invocation/a930a93e-ca74-46be-951d-9b431175ecc7
INFO: Analyzed target //src/stirling/protocol_inference:eval (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //src/stirling/protocol_inference:eval up-to-date:
  bazel-bin/src/stirling/protocol_inference/eval
INFO: Elapsed time: 0.223s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Running command line: bazel-bin/src/stirling/protocol_inference/eval --dataset /home/ddelnano/code/protocol_inference/protocol_data/packet_dataset.tsv --num_workers 8 --batch 256 --model ruleset_basic --output_dir /home/ddelnano/code/protocol_inference/
INFO: Streaming build results to: https://bb.corp.pixielabs.ai/invocation/a930a93e-ca74-46be-951d-9b431175ecc7
INFO: Build completed successfully, 1 total action
batch:0 | MeanPerClass: 0.02109375037252903
batch:1000 | MeanPerClass: 0.15883448719978333
batch:2000 | MeanPerClass: 0.1669268012046814
batch:3000 | MeanPerClass: 0.1662837713956833
MeanPerClass:  0.16844849288463593
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [4.2600e+02, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [8.7806e+04, 0.0000e+00, 1.2196e+05, 0.0000e+00, 0.0000e+00, 5.8520e+03,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.8664e+05, 0.0000e+00, 4.9680e+03, 2.0000e+00, 2.0380e+04, 6.4800e+02,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.8000e+02, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.4649e+05,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.9638e+04, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 8.4000e+01, 0.0000e+00],
        [7.4386e+04, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         1.0000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0433e+05, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.6120e+03, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 3.8400e+03]])

ddelnano@turing:~/code/pixie$ bazel run src/stirling/protocol_inference:eval  -- --dataset ~/code/protocol_inference/protocol_data/conn_dataset.tsv --num_workers 8 --batch 256 --model ruleset_basic_conn --output_dir ~/code/protocol_inference/
INFO: Streaming build results to: https://bb.corp.pixielabs.ai/invocation/17ec54b1-b24f-441a-8c59-3d184c5c96ae
INFO: Analyzed target //src/stirling/protocol_inference:eval (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //src/stirling/protocol_inference:eval up-to-date:
  bazel-bin/src/stirling/protocol_inference/eval
INFO: Elapsed time: 0.213s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Running command line: bazel-bin/src/stirling/protocol_inference/eval --dataset /home/ddelnano/code/protocol_inference/protocol_data/conn_dataset.tsv --num_workers 8 --batch 256 --model ruleset_basic_conn --output_dir /home/ddelnano/code/protocol_inference/
INFO: Streaming build results to: https://bb.corp.pixielabs.ai/invocation/17ec54b1-b24f-441a-8c59-3d184c5c96ae
INFO: Build completed successfully, 1 total action
batch:0 | MeanPerClass: 0.20000000298023224
MeanPerClass:  0.28696808218955994
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.1600e+02, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 6.2960e+03, 0.0000e+00, 0.0000e+00, 2.0000e+01,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.3200e+02, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.7200e+02, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 8.3666e+04,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.6000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 4.0000e+01, 0.0000e+00],
        [1.2234e+04, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 5.8778e+04, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.4000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,

```

</details>

### CODE REVIEW

**Comment by JamesMBartlett** [comment]
Also FYI /kind feature is for user facing features. I think we need to better document the different kinds

**Comment by ddelnano** [comment]
> Also FYI /kind feature is for user facing features. I think we need to better document the different kinds

Yea, I wasn't sure if that was an accurate label. I could see`/kind test-infra` fitting since this is how we end to end test that protocol inference works correctly if/when we make a change to it. However, a new label could be more appropriate.

What do you think about `/kind internal-tooling`?

**Comment by JamesMBartlett** [comment]
@zasgar says `/kind test-infra`

**Comment by ddelnano** [comment]
@chengruizhe and I paired on running this together and validated that our confusion matrix is as expected (connection based model has high accuracy)
latest_bi_direction

**Review by JamesMBartlett — DISMISSED** [review]

**Comment by JamesMBartlett** [comment]
> @chengruizhe and I paired on running this together and validated that the confusion matrix is as expected (connection based model has high accuracy) latest_bi_direction

Are the http2 and ssh results expected?

**Comment by ddelnano** [comment]
> Are the http2 and ssh results expected?

The ssh results are a known and not a concern since we don't support ssh as a protocol. If/when that is a possibility, we would need to reduce mux's false positive rate.

As for the http2 results, we support http2 tracing through uprobes (via grpc hooks) and therefore don't have protocol inference logic for it. However, we do want to verify that http2 isn't classified as another protocol.

Screen Shot 2023-02-03 at 3 40 37 PM

**Comment by chengruizhe** [comment]
Let's replace the confusion_matrix.jpg with the newest one, and maybe give it a better name so it's clear that it's from running the bidirectional connection model. Otherwise, LGTM.

**Review by vihangm — CHANGES_REQUESTED** [review]
Can you check why the requirements file is so long? Given the `requirement` calls in the `BAZEL.build` file, it seems like we only need to install `pandas`, `matplotlib` and `torch`.

With transitive deps this expands to just the following

```
contourpy==1.0.7
cycler==0.11.0
fonttools==4.38.0
kiwisolver==1.4.4
matplotlib==3.6.3
numpy==1.24.1
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
packaging==23.0
pandas==1.5.3
Pillow==9.4.0
pip==22.0.4
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.7.1
setuptools==56.0.0
six==1.16.0
torch==1.13.1
typing_extensions==4.4.0
wheel==0.38.4
```

**Comment by vihangm** [comment]
Can you also switch to the CPU only version of pytorch? See #771 for how to do so.

**Comment by ddelnano** [comment]
> Can you check why the requirements file is so long?

I generated the `requirements.txt` by `pip install`ing dependencies in a fresh virtualenv in order to get the script working. So I'm not sure how I ended up with a longer list of dependencies, but it should be trimmed now and my latest list matches what you found.

I've updated this to use the cpu version of pytorch as well and didn't realize that was an option.

**Comment by ddelnano** [comment]
Hm, the linter is failing with the following error, but I'm not able to reproduce that.

Screen Shot 2023-02-06 at 7 21 01 AM


```
ddelnano@turing:~/code/pixie$ ./tools/linters/bpf-test-naming.sh src/stirling/protocol_inference/BUILD.bazel
ddelnano@turing:~/code/pixie$ echo $?
0

ddelnano@turing:~/code/pixie$ arc lint


    Against which commit? public/main
 OKAY  No lint messages.

```

**Comment by JamesMBartlett** [comment]
We could add `ignore_root_user_error` for this particular problem, but there's a broader issue of running bazel queries inside the linter container image, which doesn't necessarily have all the deps we need to run bazel builds.

**Comment by JamesMBartlett** [comment]
You shouldn't have issues after either of #777 or #778

**Comment by ddelnano** [comment]
@etep @oazizi000 this is ready for review now.

**Review by etep — APPROVED** [review]

**Review by vihangm — APPROVED** [review]

**Pull request merged**
